export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST"; 
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS"; 
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL"; 


export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
